# Generated by Django 3.2.5 on 2021-08-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('idade', models.IntegerField(blank=True)),
                ('peso', models.FloatField(blank=True, max_length=30)),
                ('altura', models.FloatField(blank=True, max_length=30)),
                ('pesoPreOperatorio', models.FloatField(blank=True, max_length=30)),
                ('fumo', models.BooleanField(blank=True)),
                ('sexo', models.CharField(max_length=1)),
                ('imc', models.FloatField(blank=True, max_length=4)),
                ('ca', models.IntegerField(blank=True)),
                ('rcq', models.IntegerField(blank=True)),
                ('cx', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('tpo', models.IntegerField(blank=True)),
                ('mes1', models.FloatField(blank=True, max_length=4)),
                ('mes3', models.FloatField(blank=True, max_length=4)),
                ('mes6', models.FloatField(blank=True, max_length=4)),
                ('mes9', models.FloatField(blank=True, max_length=4)),
                ('ano1', models.FloatField(blank=True, max_length=4)),
                ('ano2', models.FloatField(blank=True, max_length=4)),
                ('ano3', models.FloatField(blank=True, max_length=4)),
                ('ano4', models.FloatField(blank=True, max_length=4)),
                ('ano5', models.FloatField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('login', models.IntegerField()),
                ('senha', models.IntegerField()),
                ('prof', models.CharField(max_length=150)),
            ],
        ),
    ]
