# Generated by Django 3.2.5 on 2021-09-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('login', models.IntegerField()),
                ('senha', models.IntegerField()),
                ('prof', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('imc', models.FloatField(blank=True, max_length=4, null=True)),
                ('altura', models.FloatField(blank=True, max_length=30, null=True)),
                ('ca', models.IntegerField(blank=True, null=True)),
                ('rcq', models.IntegerField(blank=True, null=True)),
                ('gc', models.FloatField(blank=True, max_length=5, null=True)),
                ('cx', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('alta', models.IntegerField(blank=True, null=True)),
                ('tpo', models.IntegerField(blank=True, null=True)),
                ('mes1', models.FloatField(blank=True, max_length=4, null=True)),
                ('mes3', models.FloatField(blank=True, max_length=4, null=True)),
                ('mes6', models.FloatField(blank=True, max_length=4, null=True)),
                ('mes9', models.FloatField(blank=True, max_length=4, null=True)),
                ('ano1', models.FloatField(blank=True, max_length=4, null=True)),
                ('ano2', models.FloatField(blank=True, max_length=4, null=True)),
                ('ano3', models.FloatField(blank=True, max_length=4, null=True)),
                ('ano4', models.FloatField(blank=True, max_length=4, null=True)),
                ('ano5', models.FloatField(blank=True, max_length=4, null=True)),
                ('proficional', models.ManyToManyField(to='app.Profissional')),
            ],
        ),
    ]
