# Generated by Django 3.2.7 on 2021-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='nome',
            field=models.CharField(default='', max_length=150),
        ),
    ]
