# Generated by Django 3.2.5 on 2021-07-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='altura',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='fumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='pesoPreOperatorio',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
