# Generated by Django 3.2.5 on 2021-08-17 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210705_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='ano1',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ano2',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ano3',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ano4',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ano5',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='ca',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='cx',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='imc',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='mes1',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='mes3',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='mes6',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='mes9',
            field=models.FloatField(blank=True, default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='rcq',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='sexo',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='tpo',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='altura',
            field=models.FloatField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='fumo',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='idade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='peso',
            field=models.FloatField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='pesoPreOperatorio',
            field=models.FloatField(blank=True, max_length=30),
        ),
    ]
