# Generated by Django 3.2.7 on 2021-12-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211130_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='evento',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Cirurgia', 'Cirurgia')], default='Consulta', max_length=8),
        ),
    ]
