# Generated by Django 3.2.7 on 2021-11-15 17:43

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pacientes_datanasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='dataNasc',
            field=django_cryptography.fields.encrypt(models.DateField(default='')),
        ),
    ]
