# Generated by Django 3.2.7 on 2021-11-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pacientes_datanasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='dataNasc',
            field=models.DateField(default=''),
        ),
    ]
