# Generated by Django 3.2.5 on 2021-08-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210817_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('login', models.IntegerField()),
                ('senha', models.IntegerField()),
                ('prof', models.CharField(max_length=150)),
            ],
        ),
    ]
