# Generated by Django 3.2.7 on 2021-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pacientes_datanasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.FloatField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='alta',
            field=models.DecimalField(decimal_places=0, default='', max_digits=3),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='pesoPreOp',
            field=models.FloatField(default=''),
        ),
    ]
