# Generated by Django 3.2.5 on 2021-08-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210827_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='alta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
